config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :candidates, path: 'candidates', controllers: { registrations: 'candidates/registrations',
                                                            sessions: 'candidates/sessions' }

  devise_for :employees, path: 'employees', controllers: { registrations: 'employees/registrations', 
                                            sessions: 'employees/sessions' }

  resources :candidates, only: [:show] do
    resources :enrollments, only: [:index]
  end

  resources :enrollments, only: [:show] do
    resources :proposals, only: %i[new create]
    resources :rejects, only: %i[new create]
    member do
      post 'approve'
      post 'reject'
    end
  end

  resources :proposals, only: [:show] do
    resources :accepts, only: %i[new create]
    resources :declines, only: %i[new create]
    member do
      post 'accept'
      post 'decline'
    end
  end

  resources :companies, only: %i[index new show edit update destroy] do
    resources :jobs, only: %i[new create show edit update] do
      member do
        post 'disable'
        post 'apply'
      end
    end
  end

  get 'search', to: 'home#search'
  get 'role', to: 'home#role'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company

  has_many :enrollments, dependent: :destroy
  has_many :candidates, through: :enrollments

  enum level: { intern: 0, junior: 1, full: 2, senior: 3 }
  enum type_hiring: { clt: 0, pj: 3, clt_pj: 4 }
  enum status: { active: 0, inactive: 4 }

  validates :title, :description, :salary_range, :level, :type_hiring, :requirements,
            :deadline_application, :total_vacancies, presence: true

  def applied(candidate)
    return false if candidates.exists?(candidate.id)

    Enrollment.create!(job: self, candidate: candidate)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_employee!, only: %i[new edit]
  before_action :authenticate_candidate!, only: [:apply]
  before_action :select_level, only: %i[new edit]
  before_action :select_type, only: %i[new edit]

  def index
    @jobs = Job.all
    @company = Company.find(params[:company_id])
  end

  def show
    @job = Job.find(params[:id])
    @enrollments = Enrollment.includes(:candidate).where(job: @job)
  end

  def new
    @company = Company.find(params[:company_id])
    @job = Job.new
  end

  def create
    @company = Company.find(params[:company_id])
    @job = Job.new(job_params)
    @job.company_id = @company.id

    if @job.save
      redirect_to @job.company
    else
      select_level
      select_type
      render :new
    end
  end

  def edit
    @company = Company.find(params[:company_id])
    @job = Job.find(params[:id])
  end

  def update
    @company = Company.find(params[:company_id])
    @job = Job.find(params[:id])

    if @job.update(job_params)
      redirect_to company_job_path(@job.company, @job)
    else
      select_level
      select_type
      render :edit
    end
  end

  def disable
    @job = Job.find(params[:id])
    if @job.inactive?
      redirect_to @job.company, notice: t('.already_disabled')
    elsif current_employee.company != @job.company
      redirect_to root_path, notice: t('.other_company')
    else
      @job.inactive!
      redirect_to @job.company
    end
  end

  def apply
    @job = Job.find(params[:id])

    if @job.inactive?
      redirect_to company_job_path(@job.company, @job), alert: t('.inactivated')
    elsif @job.active?
      if @job.applied(current_candidate)
        redirect_to candidate_enrollments_path(current_candidate), notice: t('.sucess')
      else
        redirect_to company_job_path(@job.company, @job), alert: t('.already_applied')
      end
    end
  end

  private

  def select_level
    @levels = Job.levels
  end

  def select_type
    @types = Job.type_hirings
  end

  def job_params
    params.require(:job).permit(:title, :level, :type_hiring, :description, :salary_range,
                                :requirements, :deadline_application, :total_vacancies, :status)
  end
end

app/views/jobs/_form.html.erb
<% if @job.errors.any? %>
  <div class="warnings">
    <%= I18n.t("errors.template.body")%>
    <ul>
      <% @job.errors.full_messages.each do |m| %>
        <li class="alert"><%= m %></li>
      <% end %>
    </ul>

  </div>
<% end %>

<%= form_with model: [@company, @job], html: { class: "create__form" } do |job| %>
  <div class="create__block title">
    <%= job.label :title, class: "create__label" %> <br>
    <%= job.text_field :title, class: "create__field" %>
  </div>

  <div class="create__block description">
    <%= job.label :description, class: "create__label" %> <br>
    <%= job.text_field :description, class: "create__field" %>
  </div>

  <div class="create__block salary">
    <%= job.label :salary_range, class: "create__label" %> <br>
    <%= job.number_field :salary_range, class: "create__field" %>
  </div>

  <div class="create__block type">
    <%= job.label :type_hiring, class: "create__label" %> <br>
    <%= job.collection_select :type_hiring, @types.map { |type| [type.first, type.first.humanize] }, 
                                                        :first, :second %> 
  </div>

  <div class="create__block level">
    <%= job.label :level, class: "create__label" %> <br>
    <%= job.collection_select :level, @levels.map{ |level| [level.first, level.first.humanize] }, 
                                                  :first, :second, prompt: "Nível da vaga" %> 
  </div>

  <div class="create__block date">
    <%= job.label :deadline_application, class: "create__label" %> <br>
    <%= job.date_field :deadline_application, class: "create__field" %>
  </div>

  <div class="create__block vacancy">
    <%= job.label :total_vacancies, class: "create__label" %> <br>
    <%= job.number_field :total_vacancies, class: "create__field" %>
  </div>

  <div class="create__block require">
    <%= job.label :requirements, class: "create__label" %> <br>
    <%= job.text_area :requirements, size: "70x15", class: "create__field" %>
  </div>

  <div class="create__block submit">
    <%= job.submit 'Salvar', class: "btn btn__secondary" %>
  </div>

<% end %>

app/views/jobs/edit.html.erb
<div class="content bg-gradient">
  <div class="container create job">
    <h2 class="create__title">Editar vaga</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/jobs/new.html.erb
<div class="content bg-gradient">
  <div class="container create job">
    <h2 class="create__title">Nova vaga</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="content bg-gray">
  <div class="container dashboard">
    <%= render 'layouts/devise_msgs' %>
    <div class="dashboard__header">
      <%= link_to 'Voltar', company_path(@job.company), class: 'btn' %>
      <h2 class="dashboard__title"><%= @job.title %></h2>
      <% if employee_signed_in? %>
        <% if current_employee.company_id === @job.company.id %>
          <div class="dashboard__settings">
            <%= link_to 'Editar', edit_company_job_path(@job.company, @job), class: "btn" %>

            <% if @job.active?%>
              <%= link_to 'Inativar', disable_company_job_path(@job.company, @job), method: :post, class: "btn btn__red" %>
            <% end %>
          </div>
        <% end %>
      <% elsif @job.active?%>
        <%= link_to 'Aplicar', apply_company_job_path(@job.company, @job), method: :post, class: "btn btn__red" %>
      <% end %>
    </div>
    
    <div class="status <%= @job.status %>">
      <span class="<%= @job.status %>"><%= Job.human_attribute_name("status.#{@job.status}") %></span>
    </div>

    <div class="dashboard__grid one__column">
      <div class="dashboard__list three__columns">
        <div class="dashboard__item desc">
          <p class="dashboard__label">Descrição: </p>
          <p class="dashboard__attribute">
            <%= @job.description %>
          </p>
        </div>

        <div class="dashboard__item salary">
          <p class="dashboard__label">Salário:</p>
          <p class="dashboard__attribute">
            <%= number_with_precision(@job.salary_range, precision: 2, separator: ',') %>
          </p>
        </div>

        <div class="dashboard__item level">
          <p class="dashboard__label">Nível: </p>
          <p class="dashboard__attribute">
            <%= Job.human_attribute_name("level.#{@job.level}") %>
          </p>
        </div>

        <div class="dashboard__item type">
          <p class="dashboard__label">Tipo de contratação: </p>
          <p class="dashboard__attribute">
            <%= Job.human_attribute_name("type_hiring.#{@job.type_hiring}") %>
          </p>
        </div>

        <div class="dashboard__item req">
          <p class="dashboard__label">Requerimentos: </p>
          <p class="dashboard__attribute">
            <%= @job.requirements %>
          </p>
        </div>

        <div class="dashboard__item date">
          <p class="dashboard__label">Data limite para aplicação: </p>
          <p class="dashboard__attribute">
            <%= @job.deadline_application.strftime("%d/%m/%Y") %>
          </p>
        </div>

        <div class="dashboard__item vacancy">
          <p class="dashboard__label">Número de vagas: </p>
          <p class="dashboard__attribute">
            <%= @job.total_vacancies %>
          </p>
        </div>
      </div>
    </div>
  </div>

  <% if employee_signed_in? && current_employee.company === @job.company %>
    <div class="container list">
      <% if @job.enrollments.empty? %>
        <h2 class="list__none">Sem inscrições no momento.</h2>
      <% else %>
        <h2 class="list__title candidate">Inscrições recebidas:</h2>
        <div class="grid">
          <% @enrollments.each do |enrollment|%>
            <div class="list__item">
              <%= link_to enrollment.candidate.name, enrollment_path(enrollment), class: "list__link" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>