config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :candidates, path: 'candidates', controllers: { registrations: 'candidates/registrations',
                                                            sessions: 'candidates/sessions' }

  devise_for :employees, path: 'employees', controllers: { registrations: 'employees/registrations', 
                                            sessions: 'employees/sessions' }

  resources :candidates, only: [:show] do
    resources :enrollments, only: [:index]
  end

  resources :enrollments, only: [:show] do
    resources :proposals, only: %i[new create]
    resources :rejects, only: %i[new create]
    member do
      post 'approve'
      post 'reject'
    end
  end

  resources :proposals, only: [:show] do
    resources :accepts, only: %i[new create]
    resources :declines, only: %i[new create]
    member do
      post 'accept'
      post 'decline'
    end
  end

  resources :companies, only: %i[index new show edit update destroy] do
    resources :jobs, only: %i[new create show edit update] do
      member do
        post 'disable'
        post 'apply'
      end
    end
  end

  get 'search', to: 'home#search'
  get 'role', to: 'home#role'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @jobs = Job.order(created_at: :desc).limit(4)
  end

  def search
    @jobs = Job.where('title like ? OR description like ?',
                      "%#{params[:q]}%", "%#{params[:q]}%")
  end
end

app/views/home/index.html.erb
<div class="content bg-gray">
  <div class="container">
    <%= render 'layouts/devise_msgs' %>

    <div class="cover">
      <h4 class="cover__title">Bem vindo ao Red Circle</h4>
      <p class="cover__subtitle">Encontre uma oportunidade e se insira neste círculo</p>
    </div>

    <div class="index">
      <% if @jobs.any? %>
        <h2 class="index__title">Oportunidades recém criadas:</h2>
        <div class="index__list">
          <% @jobs.each do |job| %>
            <div class="index__card">
              <div class="index__card__header">
                <%= link_to job.title, company_job_path(job.company, job), class: "index__card__attribute--link" %>
              </div>
              <div class="index__card__body primary">
                <div class="index__card__block">
                  <p class="index__card__label">Empresa:</p>
                  <%= link_to job.company.name, company_path(job.company), class: "index__card__attribute--link"%>
                </div>

                <div class="index__card__block">
                  <p class="index__card__label">Criado em:</p>
                  <p class="index__card__attribute"><%= job.created_at.strftime("%d/%m/%Y at %H:%M") %></p>
                </div>

                <div class="index__card__block">
                  <p class="index__card__label">Data limite para aplicar:</p>
                  <p class="index__card__attribute"><%= job.deadline_application.strftime("%d/%m/%Y") %></p>
                </div>

                <div class="index__card__block primary <%= job.status %>">
                  <span class="index__card__status <%= job.status %>"><%= Job.human_attribute_name("status.#{job.status}") %></span>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% else %>
        <h2 class="index__title">Sem vagas no momento</h2>
      <% end %>
    </div>
  </div>
</div>

app/views/home/role.html.erb
<div class="content bg-gradient">
  <div class="container category">
    <h2 class="category__title">Entrar como:</h2>

    <div class="category__list">
      <%= link_to 'Candidato', new_candidate_session_path, class: "btn btn__secondary candidate" %>
      <%= link_to 'Colaborador', new_employee_session_path, class: "btn btn__secondary employee" %>
    </div>
  </div>
</div>

app/views/home/search.html.erb
<div class="content bg-gray">
  <div class="container">
    <% if @jobs.any? %>
      <div class="cover">
        <h2 class="cover__title">Resultados da busca</h2>
      </div>
      <div class="index">
        <div class="index__list">
          <% @jobs.each do |job| %>
            <div class="index__card">
              <div class="index__card__header">
                <%= link_to job.title, company_job_path(job.company, job), class: "index__card__attribute--link" %>
              </div>
              <div class="index__card__body primary">
                <div class="index__card__block">
                  <p class="index__card__label">Empresa:</p>
                  <%= link_to job.company.name, company_path(job.company), class: "index__card__attribute--link"%>
                </div>

                <div class="index__card__block">
                  <p class="index__card__label">Criado em:</p>
                  <p class="index__card__attribute"><%= job.created_at.strftime("%d/%m/%Y at %H:%M") %></p>
                </div>

                <div class="index__card__block">
                  <p class="index__card__label">Data limite para aplicar:</p>
                  <p class="index__card__attribute"><%= job.deadline_application.strftime("%d/%m/%Y") %></p>
                </div>

                <div class="index__card__block primary <%= job.status %>">
                  <span class="index__card__status <%= job.status %>"><%= Job.human_attribute_name("status.#{job.status}") %></span>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="cover">
        <h2 class="cover__title">Desculpe, não achamos nenhuma vaga com este nome</h2>
      </div>
    <% end %>
  </div>
</div>