config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :candidates, path: 'candidates', controllers: { registrations: 'candidates/registrations',
                                                            sessions: 'candidates/sessions' }

  devise_for :employees, path: 'employees', controllers: { registrations: 'employees/registrations', 
                                            sessions: 'employees/sessions' }

  resources :candidates, only: [:show] do
    resources :enrollments, only: [:index]
  end

  resources :enrollments, only: [:show] do
    resources :proposals, only: %i[new create]
    resources :rejects, only: %i[new create]
    member do
      post 'approve'
      post 'reject'
    end
  end

  resources :proposals, only: [:show] do
    resources :accepts, only: %i[new create]
    resources :declines, only: %i[new create]
    member do
      post 'accept'
      post 'decline'
    end
  end

  resources :companies, only: %i[index new show edit update destroy] do
    resources :jobs, only: %i[new create show edit update] do
      member do
        post 'disable'
        post 'apply'
      end
    end
  end

  get 'search', to: 'home#search'
  get 'role', to: 'home#role'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :job
  belongs_to :candidate
  has_one :proposal, dependent: :destroy
  has_one :reject, dependent: :destroy

  enum status: { pending: 0, approved: 3, denied: 4 }
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_employee!, only: %i[approve reject]
  before_action :authenticate_candidate!, only: %i[index]

  def index
    @enrollments = Enrollment.includes(:job).where(candidate: current_candidate)
  end

  def show
    @enrollment = Enrollment.includes(:job, :candidate).find(params[:id])
  end

  def approve
    enrollment = Enrollment.find(params[:id])

    if enrollment.pending?
      enrollment.approved!
      redirect_to new_enrollment_proposal_path(enrollment)
    elsif enrollment.approved?
      if enrollment.proposal.blank?
        redirect_to new_enrollment_proposal_path(enrollment)
      else
        redirect_to enrollment_path(enrollment), notice: t('.already_approved')
      end
    end
  end

  def reject
    enrollment = Enrollment.find(params[:id])
    if enrollment.pending?
      enrollment.denied!
      redirect_to new_enrollment_reject_path(enrollment)
    elsif enrollment.denied?
      if enrollment.reject.blank?
        redirect_to new_enrollment_reject_path(enrollment)
      else
        redirect_to enrollment_path(enrollment), alert: t('.already_rejected')
      end
    end
  end
end

app/views/enrollments/index.html.erb
<div class="content bg-gray">
  <div class="container index">
    <%= render 'layouts/devise_msgs' %>

    <h2 class="index__title">Minhas inscrições</h2>

    <% if @enrollments.empty? %>
      <h4 class="index__none">Você ainda não se inscreveu para nenhuma vaga</h4>
    <% else %>
      <div class="index__list">
        <% @enrollments.each do |enrollment| %>
          <div class="index__card">
            <div class="index__card__header">
              <%= link_to enrollment.job.title, enrollment_path(enrollment), class: "index__card__attribute--link" %>
            </div>

            <div class="index__card__body secondary">
              <div class="index__card__block">
                <p class="index__card__label">Empresa:</p>
                <%= link_to enrollment.job.company.name, company_path(enrollment.job.company), class: "index__card__attribute--link" %>
              </div>

              <div class="index__card__block">
                <p class="index__card__label">Nº de vagas:</p>
                <p class="index__card__attribute"><%= enrollment.job.total_vacancies %></p>
              </div>

              <div class="index__card__block secondary">
                <p class="index__card__label">Status:</p>
                <p class="index__card__attribute">
                  <%= Enrollment.human_attribute_name("status.#{enrollment.status}") %>
                </p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/enrollments/show.html.erb
<div class="content bg-gray">
  <div class="container dashboard enrollment">
    <%= render 'layouts/devise_msgs' %>

    <div class="dashboard__header">
      <%= link_to 'Voltar', company_job_path(@enrollment.job.company, @enrollment.job), class: "btn" %>
      <h2 class="dashboard__title">Inscrição</h2>

      <div class="dashboard__settings">
        <% if employee_signed_in? && @enrollment.pending?%>
          <%= link_to 'Aprovar', approve_enrollment_path(@enrollment), method: :post, class: "btn btn__secondary" %>
          <%= link_to 'Reprovar', reject_enrollment_path(@enrollment), method: :post, class: "btn btn__red" %>
        <% end %>
      </div>
    </div>

    <div class="status <%= @enrollment.status %>">
      <span class="<%= @enrollment.status %>"><%= Enrollment.human_attribute_name("status.#{@enrollment.status}")%></span>
    </div>


    <div class="dashboard__grid two__columns__eql">
      <div class="dashboard__list one__column">
        <h4 class="dashboard__subtitle">Dados do candidato</h4>
        <div class="dashboard__item">
          <p class="dashboard__label">Candidato: </p>
          <p class="dashboard__attribute">
            <%= @enrollment.candidate.name %>
          </p>
        </div>

        <div class="dashboard__item">
          <p class="dashboard__label">Email: </p>
          <p class="dashboard__attribute">
            <%= @enrollment.candidate.email %>
          </p>
        </div>

        <div class="dashboard__item">
          <p class="dashboard__label">CPF: </p>
          <p class="dashboard__attribute">
            <%= number_with_delimiter(@enrollment.candidate.cpf, delimiter_pattern: /(\d{3})/) %>
          </p>
        </div>

        <div class="dashboard__item">
          <p class="dashboard__label">Telefone: </p>
          <p class="dashboard__attribute">
            <%= number_to_phone(@enrollment.candidate.phone, pattern: /(\d{2})(\d{4}|\d{5})(\d{4})$/, area_code: true) %>
          </p>
        </div>

        <div class="dashboard__item">
          <p class="dashboard__label">Biografia: </p>
          <p class="dashboard__attribute">
            <%= @enrollment.candidate.biography %>
          </p>
        </div>
      </div>

      <div class="dashboard__list two__columns">
        <h4 class="dashboard__subtitle">Dados da vaga</h4>
        <div class="dashboard__item title">
          <p class="dashboard__label">Título: </p>
          <p class="dashboard__attribute">
            <%= @enrollment.job.title %>
          </p>
        </div>

        <div class="dashboard__item level">
          <p class="dashboard__label">Nível: </p>
          <p class="dashboard__attribute">
            <%= Job.human_attribute_name("level.#{@enrollment.job.level}") %>
          </p>
        </div>

        <div class="dashboard__item desc">
          <p class="dashboard__label">Descrição: </p>
          <p class="dashboard__attribute">
            <%= @enrollment.job.description %>
          </p>
        </div>

        <div class="dashboard__item salary">
          <p class="dashboard__label">Salário: </p>
          <p class="dashboard__attribute">
            <%= number_with_precision(@enrollment.job.salary_range, precision: 2, separator: ',') %>
          </p>
        </div>

        <div class="dashboard__item type">
          <p class="dashboard__label">Tipo de contratação: </p>
          <p class="dashboard__attribute">
            <%= Job.human_attribute_name("type_hiring.#{@enrollment.job.type_hiring}") %>
          </p>
        </div>

        <div class="dashboard__item date">
          <p class="dashboard__label">Data limite para aplicar: </p>
          <p class="dashboard__attribute">
            <%= @enrollment.job.deadline_application.strftime("%d/%m/%Y") %>
          </p>
        </div>

        <div class="dashboard__item vacancy">
          <p class="dashboard__label">Nº de vagas: </p>
          <p class="dashboard__attribute">
            <%= @enrollment.job.total_vacancies %>
          </p>
        </div>

        <div class="dashboard__item req">
          <p class="dashboard__label">Requerimentos: </p>
          <p class="dashboard__attribute">
            <%= @enrollment.job.requirements %>
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="container response">
    <% if @enrollment.proposal %>
      <div class="response__item approved">
        <h2 class="response__title">Parabéns você foi aprovado, analise a proposta enviada.</h2>
        <%= link_to 'Proposta', proposal_path(@enrollment.proposal), class: "btn btn__red" %>
      </div>
    <% elsif @enrollment.denied? && @enrollment.reject %>
      <div class="response__item denied">
        <h2 class="response__title">Resposta da empresa</h2>
        <p class="response__label">Mensagem recebida em: 
          <%= @enrollment.reject.created_at.strftime("%d %B %Y às %H:%M") %>
        </p>
        <div class="response__block">
          <p class="response__label">Mensagem:</p>
          <p class="response__attribute">
            <%= @enrollment.reject.message %>
          </p>
        </div>
      </div>
    <% else %>
      <div class="response__item pending">
        <h2 class="response__title">Inscrição em análise, aguarde por uma resposta da empresa.</h2>
      </div>
    <% end %>
  </div>
</div>