config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :candidates, path: 'candidates', controllers: { registrations: 'candidates/registrations',
                                                            sessions: 'candidates/sessions' }

  devise_for :employees, path: 'employees', controllers: { registrations: 'employees/registrations', 
                                            sessions: 'employees/sessions' }

  resources :candidates, only: [:show] do
    resources :enrollments, only: [:index]
  end

  resources :enrollments, only: [:show] do
    resources :proposals, only: %i[new create]
    resources :rejects, only: %i[new create]
    member do
      post 'approve'
      post 'reject'
    end
  end

  resources :proposals, only: [:show] do
    resources :accepts, only: %i[new create]
    resources :declines, only: %i[new create]
    member do
      post 'accept'
      post 'decline'
    end
  end

  resources :companies, only: %i[index new show edit update destroy] do
    resources :jobs, only: %i[new create show edit update] do
      member do
        post 'disable'
        post 'apply'
      end
    end
  end

  get 'search', to: 'home#search'
  get 'role', to: 'home#role'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :employees, dependent: :destroy
  has_many :jobs, dependent: :destroy
  has_one_attached :logo

  validates :name, :address, :complement, :state, :city,
            :site, :cnpj, :social_media, presence: true, on: %i[edit update]
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_employee!, only: %i[edit]
  before_action :select_districts, only: %i[edit update]

  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end

  def edit
    @company = Company.find(params[:id])
    select_districts
  end

  def update
    @company = Company.find(params[:id])

    if @company.update(company_params)
      redirect_to @company
    else
      render :edit
    end
  end

  def select_districts
    @states = District.states
  end

  private

  def company_params
    params.require(:company).permit(:name, :logo, :address, :complement, :city, :state, :cnpj, :site, :social_media)
  end
end

app/views/companies/_form.html.erb
<% if @company.errors.any? %>
  <div class="warnings">
    <%= I18n.t("errors.template.body")%>
    <ul>
      <% @company.errors.full_messages.each do |m| %>
        <li class="alert"><%= m %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @company, local: false, html: { class: "create__form" } do |f| %>
<div class="create__block name">
  <%= f.label :name, class: "create__label" %> <br>
  <%= f.text_field :name, class: "create__field" %>
</div>

<div class="create__block cnpj">
  <%= f.label :cnpj, class: "create__label" %> <br>
  <%= f.number_field :cnpj, class: "create__field"  %>
</div>

<div class="create__block logo">
  <div class="container">
    <%= f.label :logo , class: "create__label" %> <br>
    <%= f.file_field :logo, class: "create__field" %>
  </div>
</div>

<div class="create__block address">
  <%= f.label :address, class: "create__label" %> <br>
  <%= f.text_field :address, class: "create__field"  %>
</div>

<div class="create__block complement">
  <%= f.label :complement, class: "create__label" %> <br>
  <%= f.text_field :complement, class: "create__field"  %>
</div>

<div class="create__block state">
  <%= f.label :state, class: "create__label" %> <br>
  <%= f.collection_select :state, @states.map{ |state| [state.sigla, state.sigla] }, :first, :second, prompt: "Estado" %>
</div>

<div class="create__block city">
  <%= f.label :city, class: "create__label"%> <br>
  <%= f.select :city, {} %>
</div>

<div class="create__block site">
  <%= f.label :site, class: "create__label" %> <br>
  <%= f.text_field :site, class: "create__field"  %>
</div>

<div class="create__block social">
  <%= f.label :social_media, class: "create__label" %> <br>
  <%= f.text_field :social_media, class: "create__field"   %>
</div>

<div class="create__block submit">
  <%= f.submit 'Salvar', class: "btn btn__secondary" %>
</div>
<% end %>

<%= content_for :javascript do %>
  <%= javascript_pack_tag 'selectCities' %>
<% end %>

app/views/companies/edit.html.erb
<div class="content bg-gradient">
  <div class="container create company">
    <% if @company.name.blank?%>
      <h2 class="create__title">Cadastrar</h2>
    <% else %>
      <h2 class="create__title">Editar <%= @company.name %></h2>
    <% end %>
    <%= render 'form' %>
  </div>
</div>

app/views/companies/index.html.erb
<div class="content bg-gray">
  <div class="container">
    <%= render 'layouts/devise_msgs' %>

    <% if @companies.empty?%>
      <div class="cover">
        <h2 class="cover__title">Nenhuma empresa cadastrada no momento</h2>
      </div>
    <% else %>
      <div class="cover">
        <h2 class="cover__title">Empresas registradas</h2>
      </div>
      <div class="index companies">
        <div class="index__list">
          <% @companies.each do |company| %>
            <div class="index__card">
              <div class="index__card__header">
                <% if company.logo.attached? %>
                  <%= image_tag company.logo %>
                <% else %>
                  <%= image_tag 'https://raw.githubusercontent.com/chrisleo-usa/final_project_fase1_td5/main/spec/support/no-image-available.jpeg' %>
                <% end %>
              </div>
              <div class="index__card__body">
                <%= link_to company.name, company_path(company), class: "index__card__attribute--link" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/companies/show.html.erb
<div class="content bg-gray">
  <div class="container dashboard">
    <%= render 'layouts/devise_msgs' %>
    <div class="dashboard__header">
      <%= link_to 'Voltar', companies_path, class: "btn" %>
      <% if !@company.name.blank?%>
        <h2 class="dashboard__title">Página da empresa <%= @company.name %></h2>
      <% end %>

      <% if employee_signed_in? %>
        <% if current_employee.company_id === @company.id && current_employee.admin === 1 %>
        <div class="dashboard__settings">
          <%= link_to 'Editar', edit_company_path, class: "btn" %>
          <%= link_to 'Deletar', company_path, method: :delete, class: "btn btn__red" %>
        </div>
        <% end %>
      <% end %>
    </div>

    <div class="dashboard__grid two__columns">
      <div class="dashboard__list">
        <div class="dashboard__item">
          <p class="dashboard__label">Empresa: </p>
          <p class="dashboard__attribute">
            <%= @company.name %>
          </p>
        </div>

        <div class="dashboard__item">
          <p class="dashboard__label">CNPJ: </p>
          <p class="dashboard__attribute">
            <%= @company.cnpj %>
          </p>
        </div>

        <div class="dashboard__item">
          <p class="dashboard__label">Endereço: </p>
          <p class="dashboard__attribute">
            <%= @company.address %>
          </p>
        </div>

        <div class="dashboard__item">
          <p class="dashboard__label">Complemento: </p>
          <p class="dashboard__attribute">
            <%= @company.complement %>
          </p>
        </div>

        <div class="dashboard__item">
          <p class="dashboard__label">Cidade: </p>
          <p class="dashboard__attribute">
            <%= @company.city %>
          </p>
        </div>

        <div class="dashboard__item">
          <p class="dashboard__label">Estado: </p>
          <p class="dashboard__attribute">
            <%= @company.state %>
          </p>
        </div>

        <div class="dashboard__item">
          <p class="dashboard__label">Site: </p>
          <p class="dashboard__attribute">
            <%= @company.site %>
          </p>
        </div>

        <div class="dashboard__item">
          <p class="dashboard__label">Rede Social: </p>
          <p class="dashboard__attribute">
            <%= @company.social_media %>
          </p>
        </div>
      </div>

      <div class="dashboard__avatar">
        <% if @company.logo.attached? %>
          <%= image_tag @company.logo %>
        <% else %>
          <%= image_tag 'https://raw.githubusercontent.com/chrisleo-usa/final_project_fase1_td5/main/spec/support/no-image-available.png' %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="container list">
    <div class="list__header">
      <h3 class="list__title">Oportunidades de emprego</h3>
      <% if employee_signed_in? %>
        <% if current_employee.company_id === @company.id && current_employee.admin == 1 %>
          <div class="list__settings">
            <%= link_to 'Registrar novo emprego', new_company_job_path(@company), class: "btn" %>
          </div>
        <% end %>
      <% end %>
    </div>

    <% if @company.jobs.empty? %>
      <p class="list__none">Sem vagas de emprego registradas no momento</p>
    <% else %>
    <div class="grid">
      <% @company.jobs.each do |job| %>
        <div class="list__item">
          <% if job.inactive? %>
            <%= link_to "#{job.title} - Inativa", company_job_path(job.company, job), class: "list__link inactive" %>
          <% else %>
            <%= link_to job.title, company_job_path(job.company, job), class: "list__link" %>
          <% end %>
        </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>